### ISSUE TITLE
AttributeError: 'MiniBatchKMeans' object has no attribute 'cluster_centers_'

### ISSUE THREAD

**Issue by harshraj32** [ammesatyajit/VideoBERT#4]
Traceback (most recent call last):
  File "VideoBERT/VideoBERT/I3D/minibatch_hkmeans.py", line 30, in <module>
    main()
  File "VideoBERT/VideoBERT/I3D/minibatch_hkmeans.py", line 26, in main
    hkmeans(root, prefix, 4, 12, batch_size, 15, save_dir, 'vecs', centroid_dir)
  File "/usr/local/lib/python3.7/dist-packages/hkmeans_minibatch/hkmeans.py", line 99, in hkmeans
    hkmeans_recursive(root, prefix, h, k, batch_size, epochs, save_dir, save_prefix, centroid_dir)
  File "/usr/local/lib/python3.7/dist-packages/hkmeans_minibatch/hkmeans.py", line 85, in hkmeans_recursive
    centroids, labelled_data = minibatch_kmeans(root, prefix, k, batch_size, epochs)
  File "/usr/local/lib/python3.7/dist-packages/hkmeans_minibatch/hkmeans.py", line 42, in minibatch_kmeans
    return kmeans.cluster_centers_, labelled_data
AttributeError: 'MiniBatchKMeans' object has no attribute 'cluster_centers_'

the line i ran without any changes :
!python3 VideoBERT/VideoBERT/I3D/minibatch_hkmeans.py -r /content/VideoBERT/VideoBERT/data/features -b 1 -s /content/VideoBERT/VideoBERT/data/kmean_vectors -c /content/VideoBERT/VideoBERT/data/centroids -p hkm

**Comment by ammesatyajit** [comment]
Your batch size seems to be 1. Ideally, it should be a multiple of how many vectors are in each file containing the feature vectors. This probably is the problem, since I had files with 20 vectors each, and I used a batch size of 500.

**Comment by ammesatyajit** [comment]
If you have a batch size of 1, the kmeans will not be able to complete because by definition it requires multiple examples to update the centroids.

**Comment by harshraj32** [comment]
yeah thanks, also what is prefix, like a string or a file containing the name of the video files?

**Comment by harshraj32** [comment]
also should  this be the output in label.json file we are creating, looks like hkmeans is predicting all zero values for the files 

"QU1Y4ogmSDE": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ],

**Comment by harshraj32** [comment]
what model file are we using in train.py file, the argument is asking for the model name or path but i havent seen any model file in this repo. 
modelchecks is the name i gave to the model 
since it is loading the model name we give from the pytorch.bin 
FileNotFoundError: [Errno 2] No such file or directory: '/content/VideoBERT/VideoBERT/modelchecks/pytorch_model.bin'

**Comment by chenjianqiang199526** [comment]
Has the problem been solved? I also had the same problem
